sudo: required

language: python

dist: trusty

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hostapd dnsmasq libdbus-1-dev libdbus-glib-1-dev

install:
  - pip install pylint tox
  - python setup.py install

script:
  - pylint --errors-only wifiphisher
  - tox -e ALL

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always
