sudo: required

language: python

dist: trusty

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hostapd dnsmasq libdbus-1-dev libdbus-glib-1-dev

install:
  - pip install tox
  - python setup.py install

script:
  - tox -e ALL

notifications:
  email:
    on_success: never
    on_failure: always
