language: python

python:
  - "2.7"

addons:
  apt_packages:
    - pandoc

install:
  - pip install tox

script:
  - tox -e ALL

after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish
